import type { Metadata } from "next";
// @ts-ignore
import "@/app/globals.css";
import Navbar from "@/components/Nav/Navbar";
import { Providers } from "@/components/Providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <section className="min-h-screen bg-background text-foreground overflow-hidden">
      <Navbar />
      {children}
    </section>
  );
}
