import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider as NextThemesProvider } from "next-themes";
import Navbar from "@/components/Nav/Navbar";
import { Toaster } from "@/components/ui/sonner"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={``}>
        <NextThemesProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
        >
          <Navbar />
          <main className="">{children}</main>
          <Toaster
            position="top-center"
            toastOptions={{
              classNames: {
                success: "bg-green-50 text-green-800",
                toast:
                  "group flex items-center gap-3 rounded-2xl border border-green-200 bg-green-50 text-green-900 p-4 shadow-lg shadow-green-100",
                title: "font-semibold text-green-800 text-sm",
                description: "text-green-700 text-xs",
                actionButton:
                  "bg-green-600 text-white hover:bg-green-700 transition-colors text-xs rounded-md px-2 py-1",
                cancelButton:
                  "bg-transparent border border-green-400 text-green-700 hover:bg-green-100 text-xs rounded-md px-2 py-1",
                icon: "text-green-600",
              },
            }}
          />
        </NextThemesProvider>
      </body>
    </html>
  );
}
