import type { Metadata } from "next";
// @ts-ignore
import "./globals.css";
import Navbar from "@/components/Nav/Navbar";
import { Providers } from "@/components/Providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={``}>
        <Providers>
          <main className="">{children}</main>
        </Providers>
      </body>
    </html>
  );
}
